# Generated by Django 4.2.7 on 2023-11-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdefinition',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportdefinition',
            name='report_type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
